name: Min_testing

on: push
jobs:
  Min_testing:
    name: Min code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      
      - name: Run Min_testing
      - uses: actions/checkout@v3
        env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
